### ISSUE TITLE
Update the repo after 2023-11-07 event (AWS Lambda functions in Rust)

### ISSUE THREAD

**Issue by tomsik68** [Rust-Slovakia/Bratislava-Rust-Meetup#12]
Add more details about talk, arrange with Frank for the slides to be inserted

**Comment by tomsik68** [comment]
@frankhorv Do you think you could insert the AWS Lambda talk slides in the repo? If not, could you share them so I can insert them here?

**Comment by frankhorv** [comment]
@tomsik68 PR #16
