### ISSUE TITLE
Talk about Unsafe

### ISSUE THREAD

**Issue by jprochazk** [Rust-Slovakia/Bratislava-Rust-Meetup#5]
Would be interesting to show how even mere mortals can write sound unsafe code.
- What `unsafe` is and isn't (raw pointers, FFI, mutating statics, etc., but does not disable the borrow checker)
- When to use it (*measureable* performance gains, implementing data structures, and as a last resort to get a *valid* program to compile with sufficient tests, miri, and preferably also fuzzing)
- Raw pointers, `PhantomData`, `UnsafeCell`
- Rust's aliasing guarantees (classic [noalias example](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=ce3ba04dac1204ccdec20a925fa2e0a8)), how easy it is to accidentally create aliasing references using raw pointers, how to prevent that (`addr_of!`, `ptr::read`, lock raw pointers behind safe interfaces that never hand out references, etc.)
- MIRI (what is it, how to use it, what kind of UB can it detect today, what are stacked borrows, what does `retag` mean, etc.)
- More resources to learn about it (Rustonomicon, [too many linked lists](https://rust-unofficial.github.io/too-many-lists/index.html), https://github.com/ctjhoa/rust-learning#unsafe, [unsafe code guidelines](https://rust-lang.github.io/unsafe-code-guidelines/))

**Comment by Kixunil** [comment]
Great topic, I've suggested the same in the discussion.

**Comment by frankhorv** [comment]
@Kixunil is this a good topic for you to prepare a talk for next meetup?

**Comment by Kixunil** [comment]
Sure, I didn't expect it to be so soon since it's advanced but if people want it, I don't mind. :)

**Comment by tomsik68** [comment]
I'm very new to `unsafe`. I spent some time toying with the noalias example above and I think it'd be great to highlight the difference between these snippets:

1:
```rust
    let a = &mut unsafe { *std::ptr::addr_of_mut!(v) };
```

2:
```rust
    let a = unsafe { &mut *std::ptr::addr_of_mut!(v) };
```

[Playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=ec25e4757c7d1405fa447550257af291)

**Comment by jprochazk** [comment]
> I think it'd be great to highlight the difference between these snippets

I don't think there's anything specific to unsafe going on here, in the first snippet you're moving out of the pointer, in the second snippet you're reborrowing the reference.

`1` can be reduced to:
```rust
let v = 100;
let a = *(&v);
```
which copies the value into a temporary place, then returns a reference to that place. It won't work for non-`Copy` types. [Playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=41bdee220effba1e08c2f895a205030b)

`2` can be reduced to:
```rust
let v = 100;
let a = &*(&v); // extra `&`
```
As long as `Deref` is not overriden for the type of `v`, it is equivalent to just:
```rust
let v = 100;
let a = &v;
```

**Comment by tomsik68** [comment]
@Kixunil Hi, we're thinking about organizing the next meet-up on Jun 28. Please let me or @frankhorv know if you're interested in giving a presentation. Please let us know until Sunday May 28 if you're interested.

**Comment by tomsik68** [comment]
Thank you for confirming, we'll be looking forward to it! Do you think your presentation could be around 30-45 minutes long? We'd like to make sure we have some time for Q&A, informal discussion and snacks.

I'm also preparing the meetup event (should be published later this week) with a section about the presentation similar to what we had last time. I'm planning to include the following: 
> Talk:  _Unsafe Rust - misconceptions, footguns, patterns_ by Martin

Let me know if this is OK with you.

**Comment by Kixunil** [comment]
Sorry, missed this in the sea of notifications. Yeah, the description is fine. I' not sure about time limit, it's a quite deep topic. I'll let you know. Perhaps worst case do it in two parts with a break?

**Comment by tomsik68** [comment]
Sure, we can have a break. I'm sure there's a lot to discuss and we can even have multiple presentations about this if it won't fit into one. We'll see how it works out in the end.

**Comment by tomsik68** [comment]
@Kixunil We're looking forward to your talk next wednesday 🎉 Feel free to arrive 10-15 minutes in advance if you want to set things up. Both Lenka and I will be available at the venue.
