### ISSUE TITLE
Update the repo after 2023-06-28 event

### ISSUE THREAD

**Issue by tomsik68** [Rust-Slovakia/Bratislava-Rust-Meetup#8]
Add more details about talk, arrange with Martin for the slides to be inserted

**Comment by tomsik68** [comment]
@kixunil Do you think you could insert the Unsafe Rust talk slides from last year in the repo? If not, could you share them so I can add them? Thanks!

**Comment by Kixunil** [comment]
https://docs.google.com/presentation/d/1_mYTCcADIBH1s1dHE7jPXny3O11DexdPEW3Q0M1ZC88/edit?usp=sharing

**Comment by tomsik68** [comment]
Thank you! Do you have a license to go with the presentation? 

I used [CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/) for [my previous talk](https://github.com/Rust-Slovakia/Bratislava-Rust-Meetup/tree/main/past_talks/2023-03-07-rust-idioms). If you'd like to do the same, I'll insert the following snippet next to your presentation:


```html
 <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://docs.google.com/presentation/d/1_mYTCcADIBH1s1dHE7jPXny3O11DexdPEW3Q0M1ZC88/edit#slide=id.p">Unsafe Rust - misconceptions, footguns, patterns</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://github.com/Kixunil">Martin Habovštiak</a> is marked with <a href="http://creativecommons.org/publicdomain/zero/1.0?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC0 1.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/zero.svg?ref=chooser-v1"></a></p> 
```

---

 <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://docs.google.com/presentation/d/1_mYTCcADIBH1s1dHE7jPXny3O11DexdPEW3Q0M1ZC88/edit#slide=id.p">Unsafe Rust - misconceptions, footguns, patterns</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://github.com/Kixunil">Martin Habovštiak</a> is marked with <a href="http://creativecommons.org/publicdomain/zero/1.0?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC0 1.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/zero.svg?ref=chooser-v1"></a></p>

**Comment by Kixunil** [comment]
CC BY-SA please.
